"""add assistant_session

Revision ID: f7ed8dd3ea71
Revises: 0003_user_avatar
Create Date: 2026-06-21 20:21:58.982033+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7ed8dd3ea71'
down_revision: Union[str, Sequence[str], None] = '0003_user_avatar'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_sessions_organization_id'), 'assistant_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assistant_sessions_user_id'), 'assistant_sessions', ['user_id'], unique=False)
    
    op.add_column('assistant_queries', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_assistant_queries_session_id'), 'assistant_queries', ['session_id'], unique=False)
    op.create_foreign_key('assistant_queries_session_id_fkey', 'assistant_queries', 'assistant_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assistant_queries_session_id_fkey', 'assistant_queries', type_='foreignkey')
    op.drop_index(op.f('ix_assistant_queries_session_id'), table_name='assistant_queries')
    op.drop_column('assistant_queries', 'session_id')
    
    op.drop_index(op.f('ix_assistant_sessions_user_id'), table_name='assistant_sessions')
    op.drop_index(op.f('ix_assistant_sessions_organization_id'), table_name='assistant_sessions')
    op.drop_table('assistant_sessions')
    # ### end Alembic commands ###
